export const metadata = {
    title: "Hive - Change Password",
    description: "Generated by create next app",
  };
  
  export default function RegisterLayout({ children }) {
    return <>{children}</>;
  }
  