import AppProvider from "@/context/appContext";
import "./globals.css";
import ApiProvider from "@/context/apiContext";
import { ThemeProvider } from "next-themes";
export const metadata = {
  title: "Hive-- Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className="bg-[#F8F8F8]">
        <ApiProvider>        
          <AppProvider>
            <ThemeProvider attribute={'class'}>
            {children}
            </ThemeProvider>         
          </AppProvider>
          </ApiProvider>
       
        
      </body>
    </html>
  );
}
