import Footer from '@/components/Footer'
import SignupCard from '@/components/SignupCard';
import Image from 'next/image';
import React from 'react'

export const metadata = {
  title: "Hive-- Sign Up",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div className='bg-white'>
        <div className='min-h-screen w-[75%] mx-auto py-10 '>
        <svg xmlns="http://www.w3.org/2000/svg" height="70" width="150" viewBox="0 0 835 190" className="logo footer__logo">
      <g fill="none">
        <g className="logo__icon">
          <path fill='#e31337' d="M157.272625,107.263942 C157.998992,107.263942 158.45262,108.051463 158.088736,108.68075 L111.33839,189.528945 C111.169808,189.820485 110.858795,190 110.522279,190 L81.9443812,190 C81.2180145,190 80.764386,189.212478 81.1282705,188.583191 L127.878616,107.734996 C128.047199,107.443456 128.358211,107.263942 128.694727,107.263942 L157.272625,107.263942 Z M129.477721,84.0901367 C129.141205,84.0901367 128.830192,83.9106218 128.66161,83.6190818 L81.1282705,1.41680884 C80.764386,0.787521511 81.2180145,0 81.9443812,0 L110.522279,0 C110.858795,0 111.169808,0.179514873 111.33839,0.471054898 L158.87173,82.6733278 C159.235614,83.3026152 158.781986,84.0901367 158.055619,84.0901367 L129.477721,84.0901367 Z"></path>
          <path fill= '#e31337' d="M135.128406 1.41635199C134.76385.787064228 135.218932 0 135.947343 0L164.565951 0C164.903712 0 165.215845.179714185 165.384888.47151174L219.873006 94.5275799C220.042331 94.8198642 220.042331 95.1801358 219.873006 95.4724201L165.384888 189.528488C165.215845 189.820286 164.903712 190 164.565951 190L135.947343 190C135.218932 190 134.76385 189.212936 135.128406 188.583648L189.342845 95 135.128406 1.41635199zM111.870216 94.5240823C112.042446 94.816752 112.043313 95.1785591 111.872487 95.4720377L57.1252257 189.528106C56.7599958 190.155572 55.8478414 190.157723 55.4796094 189.531986L.129783614 95.4759177C-.0424457704 95.183248-.0433125021 94.8214409.127512727 94.5279623L54.8747743.471894257C55.2400042-.15557243 56.1521586-.157723129 56.5203906.468014185L111.870216 94.5240823z"></path>
        </g>
        <path fillRule="nonzero" fill='#000000' d="M371.507904,36 L403.108995,36 L403.108995,152.798507 L371.507904,152.798507 L371.507904,107.24709 L326.601091,107.24709 L326.601091,152.798507 L295,152.798507 L295,36 L326.601091,36 L326.601091,78.2143177 L371.507904,78.2143177 L371.507904,36 Z M469.637608,36 L500.822895,36 L500.822895,152.798507 L469.637608,152.798507 L469.637608,36 Z M602.709958,152.798507 L556.956412,37.5016951 L556.956412,36 L591.229977,36 L619.846741,115.25613 L648.463504,36 L682.73707,36 L682.73707,37.5016951 L636.983523,152.798507 L602.709958,152.798507 Z M769.500274,124.099446 L834.505467,124.099446 L834.505467,152.798507 L737.831077,152.798507 L737.831077,36 L833.338707,36 L833.338707,64.6990618 L769.500274,64.6990618 L769.500274,80.8839979 L810.003509,80.8839979 L810.003509,107.5808 L769.500274,107.5808 L769.500274,124.099446 Z" className="logo__text text-white"></path>
      </g>
    </svg>

    <div className='grid grid-cols-1 md:grid-cols-2 mt-8'>
      <div>
        <p className='font-sans text-[44px] font-[900] text-[#212529]'>Signup for Hive</p>
        <p className='leading-relaxed font-sansRegularPro text-[18px] mt-4'>Hive powers many apps and is run completely decentralized by community members all around the world.</p>
        <p className='leading-relaxed font-sansRegularPro text-[18px] mt-4'>
        With an account, you have direct access to the ecosystem.
        </p>
        <p className='leading-relaxed font-sansRegularPro text-[18px] mt-4'>Several account creation services are provided by the community, offering you different levels of privacy and ease-of-use.</p>
        <p className='leading-relaxed font-sans text-[17px] font-[700] mt-4'>Remember: Hive does not offer "reset password" features. You. Must. Store. Your. Keys. Safely!</p>
      <p className='text-[18px] text-[#E31337] hover:text-[#9C0D26] mt-4 hover:cursor-pointer font-sansRegularPro'>Learn more about Hive</p>
      
      </div>
      <div className='flex justify-center items-center'>
        <Image src='https://signup.hive.io/images/members.svg' height={550} width={550} alt='logo'/>
      </div>

    </div>   

      <div className='py-6 mt-11'>
        <p className='font-sans text-[35px] font-[900] text-center text-[#212529]'>Registration Providers</p>
        <p className='font-sans text-[22px] font-[200] text-center'>Choose one and get your unique web 3 username!</p>

        <div className='grid justify-items-center grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 py-5 gap-3'>         

         <SignupCard title = 'InLeo'
         price = 'free'
         listItems={['Instant','Requires verification (email/google/x)']}
         />
         <SignupCard title = 'Ecency'
         price = 'free'
         listItems={['Instant','Requires verification (email)']}
         smallText={['+ in-app $2.99 with perks', '** has extra checks for free account']}/>
         <SignupCard title = 'DBuzz'
         price = 'free'
         listItems={['Instant','Requires verification (phone numner)']}
         />
         <SignupCard title = 'Hivedex.io'
         price = '$1.49'
         listItems={['Instant','Anonymous', 'Payments']}
         smallText={['BTC USDT BUSD LTC BCH XMR', ' BNB DOGE']}/>
         <SignupCard title = 'HiveWallet'
         price = '€3.49'
         listItems={['Instant','No verification', 'Payments']}
         smallText={['In-App (iOS)']}/>
         <SignupCard title = 'inji'
         price = '$3'
         listItems={['Instant','Requires login', '(email/x/metamask)','Payments']}
         smallText={['HIVE, HBD']}/>
         <SignupCard title = 'Actifit'
         price = '$2'
         listItems={['Instant','No verification', 'Payments']}
         smallText={['HIVE']}/>
         <SignupCard title = 'Discover Hive'
         price = '$2.45'
         listItems={['Instant','Email (Order Updates)', 'Payments']}
         smallText={['BTC, ETH, DAI, SOL, MATIC, BCH,', 'XRP, APE, PEPE, USDT, BUSD, LTC,', 'BCH, XMR, BNB, Mastercard, Visa,', 'Apple Pay, Google Pay, Paypal,','Binance Pay']}/>

        </div>

        <div>
          <p className='font-sans text-[30px] font-[900] text-[#212529]'>Why so many options?</p>
          <p className='leading-relaxed font-sans text-[18px] mt-4'>
          Hive accounts/addresses are easy-to-remember usernames (3 to 16 characters). They have to be created by another Hive account and have an associated cost.
        </p>
          <p className='leading-relaxed font-sans text-[18px] mt-4'>
          Some providers offer accounts for free which requires some verification to mitigate abuse, while other providers charge a small fee but require no verification.
        </p>
        <p className='font-sans text-[30px] font-[900] mt-4 text-[#212529]'>What's next?</p>
        <p className='leading-relaxed font-sans text-[18px] mt-4'>
        Once you have an account, you need to make sure your keys & password (seed) are secure.
        </p>
        <p className='leading-relaxed font-sans text-[18px] mt-4 font-[700]'>
        Please remember that Hive does not offer a "reset password" feature. It is your responsibility to save your keys and store them safely.
        </p>
        <p className='leading-relaxed font-sans text-[18px] mt-4'>
        Make sure you download them or print them out and then use one of our Wallets. Never store your keys in your email or online in any form, including inside Google Docs.
        </p>
        <button className="mt-5 block w-[30%] text-[22px] font-sans text-center bg-[#E31337] text-white active:bg-[#E31337] focus:outline-none focus:ring focus:ring-[#e313363d] border border-[#E31337] py-2 px-4 rounded-lg hover:bg-[#C0102E] hover:text-white transition-all duration-200">Next Step: Choose Wallet</button>
        <p className='font-sans text-[30px] font-[900] mt-4 text-[#212529]'>Need help?</p>
        <p className='leading-relaxed font-sans text-[18px] mt-4'>
        If you need help just drop by our chats and talk to helpful Hive community members!
        </p>
        <p className='leading-relaxed font-sans text-[18px] mt-4'>
        Join us on <span className='text-[#E31337] hover:text-[#e313363d]'>Discord</span> or on <span className='text-[#E31337] hover:text-[#e313363d]'>Telegram</span>
        </p>
        </div>
      </div>
    </div>    
    <Footer/> 
    </div>
   
  )
}

export default page
